branches:
  only:
    - master
    - travis


language: generic


jobs:
  include:
    - os: linux
      dist: bionic


before_install:
  - sudo apt-get install gfortran cmake fftw3-dev


script:
  - gfortran -v
  - g++ -v
  - cmake --version
  - echo $HOME
  - echo $PWD


# fftw
  - mkdir -p build/fftw/include
  - cd build/fftw
  - cp /usr/include/fftw3.h include/fftw3.h
  - ln -s /usr/lib/x86_64-linux-gnu lib
  - cd ../..


# test tinker9
  - cd build
  - opt=release host=1 prec=d fftw_dir=fftw cmake ..
  - make test
